In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot

c:\Users\gaurv\Downloads\STUDY\Deep Learning\Implementations\RNN\venv\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [2]:
sent=[
'the glass of milk',
'the glass of juice',
'the cup of tea',
'I am a good boy',
'I am a good developer',
'understand the meaning of words',
'your videos are good',
]

In [3]:
vocab_size = 10000

In [4]:
# One Hot Representation
one_hot_repr = [one_hot(words,vocab_size) for words in sent]
one_hot_repr

[[5946, 9839, 4482, 3300],
 [5946, 9839, 4482, 21],
 [5946, 4464, 4482, 5592],
 [6391, 9615, 5861, 9512, 6051],
 [6391, 9615, 5861, 9512, 3755],
 [5921, 5946, 8648, 4482, 472],
 [7564, 3938, 4838, 9512]]

In [5]:
# Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [7]:
sent_length = 8

In [8]:
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5946 9839 4482 3300]
 [   0    0    0    0 5946 9839 4482   21]
 [   0    0    0    0 5946 4464 4482 5592]
 [   0    0    0 6391 9615 5861 9512 6051]
 [   0    0    0 6391 9615 5861 9512 3755]
 [   0    0    0 5921 5946 8648 4482  472]
 [   0    0    0    0 7564 3938 4838 9512]]


In [9]:
# Feature Representation
dim = 10

In [20]:
model = Sequential()
model.add(Embedding(vocab_size,dim,input_shape=(sent_length,)))
model.compile('adam','mse')

c:\Users\gaurv\Downloads\STUDY\Deep Learning\Implementations\RNN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [21]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


array([[[-0.04403061, -0.0434509 , -0.03606122, -0.02744368,
          0.01965506, -0.0248996 ,  0.02727529,  0.02531173,
         -0.03976103, -0.04287262],
        [-0.04403061, -0.0434509 , -0.03606122, -0.02744368,
          0.01965506, -0.0248996 ,  0.02727529,  0.02531173,
         -0.03976103, -0.04287262],
        [-0.04403061, -0.0434509 , -0.03606122, -0.02744368,
          0.01965506, -0.0248996 ,  0.02727529,  0.02531173,
         -0.03976103, -0.04287262],
        [-0.04403061, -0.0434509 , -0.03606122, -0.02744368,
          0.01965506, -0.0248996 ,  0.02727529,  0.02531173,
         -0.03976103, -0.04287262],
        [-0.02938356,  0.00076536, -0.0478016 , -0.00465096,
         -0.0238128 , -0.01619065, -0.00320375, -0.02756645,
         -0.04030541,  0.01661747],
        [-0.04697257,  0.02095095,  0.0179552 ,  0.02523751,
          0.03083552, -0.03749432, -0.03007975,  0.01442292,
          0.02878774, -0.02245398],
        [ 0.02002852, -0.00028477,  0.01475604, -0.0

In [23]:
embedded_docs[0]

array([   0,    0,    0,    0, 5946, 9839, 4482, 3300], dtype=int32)

In [24]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step


array([[-0.04403061, -0.0434509 , -0.03606122, -0.02744368,  0.01965506,
        -0.0248996 ,  0.02727529,  0.02531173, -0.03976103, -0.04287262],
       [-0.04403061, -0.0434509 , -0.03606122, -0.02744368,  0.01965506,
        -0.0248996 ,  0.02727529,  0.02531173, -0.03976103, -0.04287262],
       [-0.04403061, -0.0434509 , -0.03606122, -0.02744368,  0.01965506,
        -0.0248996 ,  0.02727529,  0.02531173, -0.03976103, -0.04287262],
       [-0.04403061, -0.0434509 , -0.03606122, -0.02744368,  0.01965506,
        -0.0248996 ,  0.02727529,  0.02531173, -0.03976103, -0.04287262],
       [-0.02938356,  0.00076536, -0.0478016 , -0.00465096, -0.0238128 ,
        -0.01619065, -0.00320375, -0.02756645, -0.04030541,  0.01661747],
       [-0.04697257,  0.02095095,  0.0179552 ,  0.02523751,  0.03083552,
        -0.03749432, -0.03007975,  0.01442292,  0.02878774, -0.02245398],
       [ 0.02002852, -0.00028477,  0.01475604, -0.03366327, -0.02300185,
         0.03766007,  0.03378591, -0.04314772